name: Build and push

on:
    push:
        branches:
            - main
        paths:
            - "src/**"
            - "package.json"
            - "pnpm-lock.yaml"
            - "pnpm-workspace.yaml"
            - "action.yml"

jobs:
    build-and-push:
        name: Build and push
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Set up node.js
              uses: actions/setup-node@v6

            - uses: pnpm/action-setup@v4
              name: Set up pnpm

            - name: Install dependencies
              run: pnpm i

            - name: Save commit SHA
              run: |
                  export BUILD_COMMIT_SHA=$(git rev-parse HEAD)
                  echo ${BUILD_COMMIT_SHA}
                  echo "BUILD_COMMIT_SHA=${BUILD_COMMIT_SHA}" >> ${GITHUB_ENV}

            - name: Build project
              run: pnpm run build

            - name: Backup dist to a temporary location
              run: mv dist /tmp/new_dist

            - name: Fetch 'dist' branch
              run: git fetch origin dist:dist || git switch --orphan dist

            - name: Switch to 'dist' branch
              run: git switch dist

            - name: Remove current dist
              run: rm -rf dist || true

            - name: Restore dist from temporary location
              run: mv /tmp/new_dist dist

            - name: Update 'user.name' and 'user.email'
              run: |
                  git config --local user.name "github-actions[bot]"
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Stage 'dist'
              run: git add -f dist

            - name: Check git status
              run: git status

            - name: Commit 'dist'
              run: 'git commit --allow-empty -m "Build: ${BUILD_COMMIT_SHA}"'

            - name: Push to 'dist' branch
              run: git push -f origin dist
