name: Run 'my-gha'
on:
    workflow_dispatch:

    workflow_run:
        workflows: ["Build and push to 'dist' branch"]
        types:
            - completed

jobs:
    run-action:
        name: Run 'my-gha'
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

        steps:
            - uses: "romeosarkar10x-learn/my-gha@dist"
              name: Run 'my-gha'
              with:
                  name: "Romeo Sarkar"
                  languages: "ASM,C,C++,Java,JavaScript,TypeScript,Go,Python"
